language: php
before_script:
- curl -s http://getcomposer.org/installer | php
- php composer.phar install
php:
- "5.5"
- "5.4"
script: php vendor/bin/phpunit --colors --coverage-text --configuration tests/phpunit.xml.dist  tests/